# Generated by Django 4.2.13 on 2026-05-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_days', models.PositiveIntegerField()),
                ('requires_document', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_requested', models.PositiveIntegerField(default=0)),
                ('leave_address', models.TextField()),
                ('phone_during_leave', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SUPERVISOR_REVIEW', 'Supervisor Review'), ('HR_REVIEW', 'HR Review'), ('HR_CHECK', 'HR Check'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('supervisor_recommended_days', models.PositiveIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('leave_entitlement', models.PositiveIntegerField(blank=True, null=True)),
                ('accumulated_with_permission', models.PositiveIntegerField(default=0)),
                ('leave_taken_this_year', models.PositiveIntegerField(blank=True, null=True)),
                ('total_days_due', models.PositiveIntegerField(blank=True, null=True)),
                ('balance_remaining', models.IntegerField(blank=True, null=True)),
                ('resume_date', models.DateField(blank=True, null=True)),
                ('leave_allowance_ksh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leaves.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_table', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('II', 'Part II — Supervisor'), ('III', 'Part III — HR Review'), ('IV', 'Part IV — HR Allowance'), ('V', 'Part V — HR Officer Verify'), ('VI', 'Part VI — Head HR Final')], max_length=5)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaves.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_entitlement', models.PositiveIntegerField(default=0)),
                ('accumulated_with_permission', models.PositiveIntegerField(default=0)),
                ('taken', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
